version: '3.8'

services:
    web:
        build: .
        volumes:
            - .:/usr/src/app/
        ports:
            - 5000:5000
        environment:
            PORT: 5000
            FLASK_DEBUG: 1
